server {
    listen 80;
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    # FRONTEND (React)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # SOCKET.IO (node)
    location /socket.io/ {
        proxy_pass http://api-node:5000/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # NODE API
    location /api/ {
        proxy_pass http://api-node:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # LARAVEL API
    location ^~ /laravel-api/ {
        alias /var/www/html/public/;
        try_files $uri $uri/ @laravel;

        location ~ \.php$ {
            fastcgi_pass api-laravel:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        }
    }

    location @laravel {
        rewrite ^/laravel-api/(.*)$ /laravel-api/index.php?/$1 last;
    }
}
